version: "3.9"
services: 
  database: 
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment: 
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
       - ./postgres:/var/lib/postgresql/data
    ports:
       - "5432:5432"
